### ISSUE TITLE
Strange behaviour at the end of lines

### ISSUE THREAD

**Issue by parkr** [mmcgrana/textmate-clojure#2]
I just installed this into TextMate 2. Looks like the grammar thinks something is weird.

![textmate-clojure-issue](http://f.cl.ly/items/3o2x3b0A3X3c0a3L0D16/textmate-clojure-issue.png)

**Comment by mmcgrana** [comment]
That is indeed weird. I don't have TextMate 2 and therefore can't promise that I'll be able to personally help on this one, but I can try to talk it out here. Do you know what the pink color in your image corresponds to in your highlighting config? We might be able to work backwards from that to the problem. Also, you might try sort of binary searching the text in that file to see what exact incremental changes cause it to go from correct to incorrect highlighting.

Sorry I can't provide an immediate answer!

**Comment by parkr** [comment]
No problem. Thanks for the quick response.

The pink/red color corresponds to the indication that there is an error in my syntax. If I get rid of the newlines (even though it's still valid with the newlines), the error goes away:

![textmate-clojure-issue2](http://f.cl.ly/items/1O1J0z3j1C363k3F423B/textmate-clojure-issue2.png)

**Comment by kelvinpompey** [comment]
I fixed the problem by editing the bundle to not match the whitespace. Change the whitespace item in the clojure language grammar to: 

```
    whitespace = {
        name = 'invalid.trailing-whitespace';
        match = '^$';
    };
```

![Screen Shot 2013-01-06 at 4 19 16 PM](https://f.cloud.github.com/assets/364535/46260/9643dd28-583e-11e2-9587-15ce70f117cb.png)
