### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nathansobo** [mmcgrana/textmate-clojure#3]
Would you be willing to add a `LICENSE` file to this project?

**Comment by pchaigno** [comment]
@mmcgrana We would like to use your lexer at github/linguist to highlight Clojure code on GitHub. Any chance you could pick a license from here: http://choosealicense.com?

**Comment by mmcgrana** [comment]
Sorry I missed this issue earlier. Added MIT.

**Comment by pchaigno** [comment]
No problem. Thanks!
